run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gosec
    - gocritic
    - gocyclo
    - goconst
    - godot
    - nolintlint

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
      - name: var-naming
        severity: warning
      - name: package-comments
        severity: warning
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 2
    min-occurrences: 2

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec