version: 2

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gosec
    - goconst

linters-settings:
  goconst:
    min-len: 2
    min-occurrences: 2

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec